### PR TITLE
Separate lint steps in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
🎉 To make them visible.

kép

### CODE REVIEW

**Comment by szepeviktor** [comment]
@marekdedic What do you think about this one?

**Comment by marekdedic** [comment]
Hi,
thinking about it... On the one hand, yes, it makes it more visible. On the other, it makes it more tied to the specific linters...

**Comment by szepeviktor** [comment]
I let you cook in this soup.

**Comment by marekdedic** [comment]
Soup boiled. Thanks for the PR, I am not going to merge it however.

**Comment by szepeviktor** [comment]
The mother of all PHP package templates https://github.com/ergebnis/php-library-template does this way:
every tool runs in a separate **job**.

**Comment by marekdedic** [comment]
Interesting template, thanks! But a huge overkill IMO :D

**Pull request closed without merging**
